### PR TITLE
WIP: refactoring client, nodes, cerebro, master and kibana definition

### PR DESCRIPTION
**Pull request by gianrubio**
@stevesloka I'd like to get some inputs from this PR before I keep working on it. It redefine objects specs to make easier to customise values.

#163

### CODE REVIEW

**Comment by gianrubio** [comment]
Should I bump the api version to v2?

**Comment by pieterlange** [comment]
> Should I bump the api version to v2?

Since this changes the spec all over the place, an API version bump does seem in order. :)

Maybe it makes sense to document the benefits of the API change (making it more future proof, etc) before bumping.

**Comment by stevesloka** [comment]
@gianrubio Would you mind coming up with a design doc first? It might help to go over the design ideas before starting to implement code.

**Comment by gianrubio** [comment]
ok @stevesloka, I did a proposal on #184

**Pull request closed without merging**
