### PR TITLE
Upgrade to Kubernetes 1.17.0

### PR DESCRIPTION
**Pull request by cedbossneo**
- Switch to Go Modules
- Remove vendor directory

### CODE REVIEW

**Comment by brianberzins** [comment]
I'm pretty sure this is exactly what I just ran into. For anyone else trying to figure out what's happening, in kubernetes 1.17.0 deployments moved from beta into `app/v1` From my troubleshooting, it looks like the operator fails to create the cluster with the following logs:

```
time="2020-01-14T22:21:59Z" level=error msg="Could not create client deployment: the server could not find the requested resource"
time="2020-01-14T22:21:59Z" level=error msg="Error creating client deployment the server could not find the requested resource"
time="2020-01-14T22:21:59Z" level=error msg="the server could not find the requested resource"
```

Just trying to add some context in case someone else runs across the same thing.

👍 to @cedbossneo for the PR, and hope to see it merged in the near future!

**Comment by kfox1111** [comment]
That would be my guess. In 1.16 you can reenable the disabled apis. I'm guessing you can in 1.17. You might be able to do that to verify its that issue.

**Comment by brianberzins** [comment]
Honestly, I'm a bit confused here... because I don't understand why this would be working in 1.16 either... because it looks like `extensions/v1beta1/deployments` was removed in 1.16.0...

I'm still digging on my side to see what's actually happening.

**Comment by diegosucaria** [comment]
Hello everyone, I'm new with helm charts, how can I use the code from this PR?
Since this repo hasn't been updated for a long time...

Can I consume the code from the branch directly?
like: helm repo add es-operator https://raw.githubusercontent.com/cedbossneo/elasticsearch-operator/master/charts/ 

Any help is appreciated! thanks

**Comment by nikogura** [comment]
No, you'd have to compile the operator from the source branch.  The resource types in the code are incompatible with k8s v1.17.

I've done just that - but am not yet 100% successful.  Will update if things change.

**Comment by nikogura** [comment]
Ok. This is now working for me with kubernetes v1.17.7: https://github.com/nikogura/elasticsearch-operator. 

You do, however have to run `sudo sysctl -w vm.max_map_count=262144` on both the worker and master nodes for the pods to be able to start.  (Or at least _I_ did, using the latest Ubuntu ami in AWS)

It builds on the excellent work by @cedbossneo ( thank you very much sir!).   I've updated the charts, and the dockerfile so that it can build locally if need be.  

I'll PR my changes back to @cedbossneo for now, and to this repo when this PR is reviewed.

Please let me know if I can be of any help!  Love this project.

**Pull request closed without merging**
