### PR TITLE
Fix PVC selection to enable update of VolumeReclaimPolicy of PV

### PR DESCRIPTION
**Pull request by splisson-altair**
The function was using the hardcoded example-elasticsearch cluster name

### CODE REVIEW

**Comment by gianrubio** [comment]
This PR broke the master branch, elasticsearch nodes never start up because Probes are failing. If you didn't setup the `use-ssl` flag golang will assume the var value as false

```
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason      Age                  From                                                Message
  ----     ------      ----                 ----                                                -------
  Warning  Unhealthy   5m (x2941 over 17h)  kubelet, ip-10-120-0-10.eu-west-1.compute.internal  Liveness probe failed: Get http://100.96.3.11:9200/_nodes/_local: EOF
  Warning  FailedSync  2s (x2476 over 17h)  kubelet, ip-10-120-0-10.eu-west-1.compute.internal  Error syncing pod
```

**Comment by gianrubio** [comment]
@splisson-altair you also missed to disable ssl in cerebro deployment

**Comment by splisson-altair** [comment]
the use-ssl part should not have ended up here, my bad.
I'll have a look, thanks

**Comment by splisson-altair** [comment]
@gianrubio what part is SSL in cerebro deployment ?

**Comment by splisson-altair** [comment]
I don't see where SSL is involved in the deployment of cerebro though.

**Comment by splisson-altair** [comment]
I have not figured out how to make use-ssl default to yes since we're using struct without constructor for the cluster spec.

**Pull request merged**
