### PR TITLE
Update Helm Chart Operator image version to 0.2.0 Release

### PR DESCRIPTION
**Pull request by kskewes**
WFM. 
@komljen would you like to check considering you're listed as chart maintainer?

Note I use slightly different node numbers, 2 data and 3 master. 
I really need to use an override for names though... :sweat_smile: 
```
NAME                                                        READY     STATUS    RESTARTS   AGE
pod/cerebro-dev-es-cluster-798cfccbb-zsdxk             1/1       Running   0          17m
pod/es-client-dev-es-cluster-59d58cdb-2wtvq            1/1       Running   0          17m
pod/es-client-dev-es-cluster-59d58cdb-ksdkt            1/1       Running   0          17m
pod/es-data-dev-es-cluster-ibmc-file-retain-gold-0     1/1       Running   0          17m
pod/es-data-dev-es-cluster-ibmc-file-retain-gold-1     1/1       Running   0          15m
pod/es-master-dev-es-cluster-ibmc-file-retain-gold-0   1/1       Running   0          17m
pod/es-master-dev-es-cluster-ibmc-file-retain-gold-1   1/1       Running   0          15m
pod/es-master-dev-es-cluster-ibmc-file-retain-gold-2   1/1       Running   0          6m
pod/kibana-dev-es-cluster-6467c6947d-s7b9l             1/1       Running   0          17m

NAME                                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/cerebro-dev-es-cluster                   ClusterIP   172.21.161.102   <none>        80/TCP     17m
service/elasticsearch-dev-es-cluster             ClusterIP   172.21.157.215   <none>        9200/TCP   17m
service/elasticsearch-discovery-dev-es-cluster   ClusterIP   172.21.110.141   <none>        9300/TCP   17m
service/es-data-svc-dev-es-cluster               ClusterIP   172.21.117.161   <none>        9300/TCP   17m
service/kibana-dev-es-cluster                    ClusterIP   172.21.76.156    <none>        80/TCP     17m

NAME                                                                                  STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
persistentvolumeclaim/es-data-es-data-dev-es-cluster-ibmc-file-retain-gold-0     Bound     pvc-52131e4f-8b14-11e8-928f-d2b4fe970851   20Gi       RWO            ibmc-file-retain-gold   17m
persistentvolumeclaim/es-data-es-data-dev-es-cluster-ibmc-file-retain-gold-1     Bound     pvc-ad812abf-8b14-11e8-928f-d2b4fe970851   20Gi       RWO            ibmc-file-retain-gold   15m
persistentvolumeclaim/es-data-es-master-dev-es-cluster-ibmc-file-retain-gold-0   Bound     pvc-520fd30f-8b14-11e8-928f-d2b4fe970851   20Gi       RWO            ibmc-file-retain-gold   17m
persistentvolumeclaim/es-data-es-master-dev-es-cluster-ibmc-file-retain-gold-1   Bound     pvc-a59e46ff-8b14-11e8-928f-d2b4fe970851   20Gi       RWO            ibmc-file-retain-gold   15m
persistentvolumeclaim/es-data-es-master-dev-es-cluster-ibmc-file-retain-gold-2   Bound     pvc-eae2cc43-8b15-11e8-928f-d2b4fe970851   20Gi       RWO            ibmc-file-retain-gold   6m

```

### CODE REVIEW

**Comment by komljen** [comment]
So, basically, you only want to use the new image tag for the operator?

**Comment by kskewes** [comment]
Thanks. I contemplated it both ways and went through some of the revision history trying to ascertain a pattern or intended scheme. 
Given the three different deployable elements (2 helm charts, one k8s manifest), maybe it would be easier for new users to sync versioning. 
No strong feelings either way, happy to amend.

**Comment by kskewes** [comment]
FWIW, I've gone back to using vanilla K8s manifests. Kibana and Cerebro services are now included and we have changed tooling here. So we can close this PR if you prefer.

**Comment by komljen** [comment]
With this PR you updated image tag version, but you can change it on the fly with `--set image.tag=0.2.0`. So, I don't understand what was the real issue.

**Comment by kskewes** [comment]
I've been tending to update main charts when the image etc reach stable prod for us. Could be called meta work I guess. 
Let's flag it.

**Pull request closed without merging**
